# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class Items(BaseModel):
    manifestId: Annotated[str, Field(description="Unique identifier of a matched C2PA Manifest")]
    endpoint: Annotated[
        str | None,
        Field(
            description="Endpoint of a Soft Binding Resolution API from which the C2PA Manifest may be obtained. If the endpoint is absent then the C2PA Manifest is available from same endpoint the query was sent to using the /manifests endpoint"
        ),
    ] = None
    similarityScore: Annotated[
        int | None,
        Field(
            description="An integer score in the range (0-100) representing the strength of match, if appropriate, where 0 is the weakest possible match and 100 is the strongest possible match",
            ge=0,
            le=100,
        ),
    ] = None


class DetailItem(BaseModel):
    loc: list[str | int]
    msg: str


class Error(BaseModel):
    detail: Annotated[str | list[DetailItem], Field(description="A message, or a list of parameter errors")]


class IsccMatch(Items):
    endpoint: Annotated[
        str,
        Field(
            description="Address on this resolver from which the manifest is fetched, specific to the declaration",
            examples=["https://c2pa.iscc.io/v1/iscc/maigkv5faaxoxyab"],
        ),
    ]
    similarityScore: Annotated[
        int,
        Field(
            description="100 for an equal Instance-Code, otherwise the best unit similarity, at most 99", ge=0, le=100
        ),
    ]
    isccId: Annotated[
        str,
        Field(
            description="Extension. ISCC-ID of the declaration that points to this manifest.",
            examples=["ISCC:MAIGKV5FAAXOXYAB"],
            pattern="^ISCC:[A-Z2-7]{16}$",
        ),
    ]


class IsccQueryResult(BaseModel):
    matches: list[IsccMatch]
