# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class Watermarks(BaseModel):
    alg: Annotated[
        str, Field(description="Unique identifier of a fingerprint algorithm", examples=["foo.bar.watermark.1"])
    ]


class Fingerprint(BaseModel):
    alg: Annotated[
        str, Field(description="Unique identifier of a watermark algorithm", examples=["foo.bar.fingerprint.1"])
    ]


class SoftBindingAlgList(BaseModel):
    watermarks: list[Watermarks] | None = None
    fingerprints: list[Fingerprint] | None = None


class SoftBindingQuery(BaseModel):
    alg: Annotated[
        str, Field(description="A string identifying the soft binding algorithm and version of that algorithm used")
    ]
    value: Annotated[
        str,
        Field(
            description="A base64-encoded string describing, in algorithm specific format, the value of the soft binding to be used as the query"
        ),
    ]


class Match(BaseModel):
    manifestId: Annotated[str, Field(description="Unique identifier of a matched C2PA Manifest")]
    endpoint: Annotated[
        str | None,
        Field(
            description="Endpoint of a Soft Binding Resolution API from which the C2PA Manifest may be obtained. If the endpoint is absent then the C2PA Manifest is available from same endpoint the query was sent to using the /manifests endpoint"
        ),
    ] = None
    similarityScore: Annotated[
        int | None,
        Field(
            description="An integer score in the range (0-100) representing the strength of match, if appropriate, where 0 is the weakest possible match and 100 is the strongest possible match",
            ge=0,
            le=100,
        ),
    ] = None


class SoftBindingQueryResult(BaseModel):
    matches: list[Match] | None = None


class Status(StrEnum):
    ok = "ok"
    degraded = "degraded"
    down = "down"


class ServiceStatus(BaseModel):
    status: Annotated[Status, Field(description="Current operational status of the service", examples=["ok"])]
    timestamp: Annotated[
        AwareDatetime | None,
        Field(description="Time at which the status was generated", examples=["2024-01-01T00:00:00Z"]),
    ] = None


class ServiceCapabilities(BaseModel):
    c2paSpecificationVersion: Annotated[
        str,
        Field(
            description="Version of the C2PA specification whose Soft Binding Resolution API semantics are implemented by this service endpoint, formatted as a Semantic Versioning (SemVer) string per https://semver.org. This value is not an independent API version and shall match the OpenAPI info.version field for the API definition implemented by the service endpoint",
            examples=["2.4.0"],
            pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$",
        ),
    ]
    supportedCapabilities: Annotated[
        list[str],
        Field(
            description="List of optional capabilities supported by this service instance. Absence of a capability name from this list unambiguously indicates the capability is not supported. Clients should ignore unknown values, allowing future versions of this specification to introduce new capability names without breaking existing implementations. Known values are: queryByContent (POST /matches/byContent), queryByReference (POST /matches/byReference), storeManifests (POST /manifests and DELETE /manifests/{manifestId}), storeBindings (POST and PUT /bindings).",
            examples=[["queryByContent", "storeManifests", "storeBindings"]],
        ),
    ]


class WellKnownDiscovery(BaseModel):
    apiEndpoint: Annotated[
        AnyUrl,
        Field(
            description="Base URI of the versioned C2PA Soft Binding Resolution API. The path segment, such as /v1, identifies the major compatibility version of the HTTP API surface and does not change for every C2PA specification minor or patch release",
            examples=["/v1"],
        ),
    ]
    c2paSpecificationVersion: Annotated[
        str,
        Field(
            description="Version of the C2PA specification whose Soft Binding Resolution API semantics are implemented by this service endpoint, formatted as a Semantic Versioning (SemVer) string per https://semver.org. This value is not an independent API version and shall match the OpenAPI info.version field for the API definition implemented by the service endpoint",
            examples=["2.4.0"],
            pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$",
        ),
    ]
    capabilitiesEndpoint: Annotated[
        AnyUrl | None,
        Field(description="URI of the capabilities endpoint for this service", examples=["/v1/services/capabilities"]),
    ] = None
    statusEndpoint: Annotated[
        AnyUrl | None,
        Field(description="URI of the status endpoint for this service", examples=["/v1/services/status"]),
    ] = None
